# Generated by Django 5.0.1 on 2024-01-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('price', models.TextField(null=True)),
            ],
        ),
    ]
